name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: mcr.microsoft.com/vscode/devcontainers/python:3

    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        # Bazel version to install e.g. 1.2.1, 2.0.0, ...
        version: 3.7.1 # optional, default is 2.0.0

    - name: Run tests
      run: bazel test //...