name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # TODO(Jonathon): I think the gcc version is not high enough:
    # https://github.com/thundergolfer/dropbox-style-python-repo/runs/1479791272?check_suite_focus=true
    runs-on: ubuntu-20.04

    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        # Bazel version to install e.g. 1.2.1, 2.0.0, ...
        version: 3.7.1 # optional, default is 2.0.0

    - name: Run tests
      run: bazel test //...